### ISSUE TITLE
sdformat: README

### ISSUE THREAD

**Issue by audrow** [gazebosim/garden-tutorial-party#1928]
## Setup
- Os: Ubuntu Focal
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/libs/sdformat)
- [Source](https://github.com/gazebosim/sdformat/blob/sdf13/README.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by adityapande-1995** [comment]
Looks good !
