### ISSUE TITLE
docs: install_osx

### ISSUE THREAD

**Issue by audrow** [gazebosim/garden-tutorial-party#1977]
## Setup
- Os: MacOS 11 (Big Sur)
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/docs/garden/install_osx)
- [Source](https://github.com/gazebosim/docs/tree/master/garden/install_osx.md)

## Checks
- [x] **Instructions work**
- [ ] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by azeey** [comment]
Installation works, but running `gz` results in the following error message:

```
I cannot find any available 'gz' command:
        * Did you install any Gazebo library?
        * Did you set the GZ_CONFIG_PATH environment variable?
            E.g.: export GZ_CONFIG_PATH=$HOME/local/share/gz
```

**Comment by azeey** [comment]
https://github.com/osrf/homebrew-simulation/pull/2039
