### ISSUE TITLE
gz-fuel-tools: README

### ISSUE THREAD

**Issue by audrow** [gazebosim/garden-tutorial-party#2077]
## Setup
- Os: Ubuntu Focal
- BuildType: Binary

## Links
- [Live](https://gazebosim.org/libs/fuel_tools)
- [Source](https://github.com/gazebosim/gz-fuel-tools/blob/gz-fuel-tools8/README.md)

## Checks
- [x] **Instructions work**
- [x] **Images (if there are any) match the result**

---

*You can find the code used to generate this test case [here](https://github.com/audrow/yatm)*

**Comment by nkoenig** [comment]
Requires this PR: https://github.com/gazebosim/gz-fuel-tools/pull/295
